### ISSUE TITLE
Gentle request for a 1.20.2 version - no pressure!

### ISSUE THREAD

**Issue by LessThanBenji** [KingContaria/FastQuit#39]
Hi, I hate it when people nag for updates, but this mod is just so useful I have to know - is a bump up to 1.20.2 planned? No stress if it's not.

**Comment by KingContaria** [comment]
Hey, right now my main focus is on other mods, afaik the available 1.20.1 version should also just work on 1.20.2, which is why i haven't bothered pushing out an update yet, should probably get to that at some point tho
If you have any issues using the latest version on 1.20.2 however, please don't hesitate to let me know!

**Comment by LessThanBenji** [comment]
The 1.20.1 version is indeed working fine on 1.20.2 from what I've experienced so far - thanks for letting me know about that! Only caveat is the game does freeze for a second or two each time you click "save and quit to title" (which I don't recall happening in the 1.19.4 version I was using prior) but after that it catches up and works like a charm - still light-years faster than vanilla 😆

**Comment by LessThanBenji** [comment]
Ignore that caveat I mentioned, I've realized just now that brief pause is the work of [Seamless Loading Screen](https://modrinth.com/mod/seamless-loading-screen) doing its thing (taking a screenshot) and has nothing to do with FastQuit whatsoever. Apologies, and thanks again!

**Comment by MisileLab** [comment]
if 1.20.1 version can be using in 1.20.2, can you add 1.20.2 version in your modrinth mod version?

**Comment by Felix14-v2** [comment]
1.20.4 is broken tho
